version: 2
jobs:
  build:
    macos:
      xcode: "9.2.0"
    shell: /bin/bash --login -eo pipefail
    steps:
    - checkout
    - run:
        name: Install gems
        command: bundle check || bundle install
    - run:
        name: Run tests
        environment:
        - LC_ALL: en_US.UTF-8
        - LANG: en_US.UTF-8
        command: bundle exec fastlane test
    - run:
        name: Send coverage report to Coveralls
        command: bundle exec slather
